# Generated by Django 4.1.4 on 2023-01-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('proteins', models.FloatField(verbose_name='белки')),
                ('fats', models.FloatField(verbose_name='жиры')),
                ('carbohydrates', models.FloatField(verbose_name='углеводы')),
                ('energy', models.FloatField(verbose_name='энергетическая ценность')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='название')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('proteins', models.FloatField(verbose_name='белки')),
                ('fats', models.FloatField(verbose_name='жиры')),
                ('carbohydrates', models.FloatField(verbose_name='углеводы')),
                ('energy', models.FloatField(verbose_name='энергетическая ценность')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='масса')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='app_recipes.product', verbose_name='продукт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='app_recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
    ]
